# Matrices en Python

### Primero importamos las librerías que utilizaremos para el proceso:

In [61]:
import numpy as np
from scipy import linalg
from IPython.core.display import display, HTML

### Para representar una matriz en Python veremos las siguientes formas:

#### Primero una matriz 2x2:

\begin{vmatrix}
1 & 3\\ 
7 & 9
\end{vmatrix}

In [17]:
a = np.mat('[1 3;7 9]')  #Esta es una matriz 2x2

In [6]:
print(a)

[[1 3]
 [7 9]]


#### Para construir una matriz nxn, podemos utilizar la siguiente nomenclatura:

In [18]:
c = matrix([[1,3,-5],[3,4,2],[-5,2,0]])

In [19]:
print(c)

[[ 1  3 -5]
 [ 3  4  2]
 [-5  2  0]]


####Por defecto la matriz identidad viene cargada desde el paquete scipy con la extensión linalg (Regresión Lineal, en este caso tenemos la matriz identidad como I y  la transpuesta de una matriz cualquiera como T, pero es importante recordar que se los podrá utilizar en el producto con otras matrices, y no por sí solos.

#### Para conocer un poco más de la librería puedes visitar:
[Scipy](https://docs.scipy.org/doc/scipy/reference/linalg.html)

In [20]:
###Matriz identidad:

In [26]:
print(a.I) #Producto la matriz identidad de a

[[-0.75        0.25      ]
 [ 0.58333333 -0.08333333]]


In [25]:
print(a.T) #Producto con la matriz transpuesta de a

[[1 7]
 [3 9]]


In [58]:
###Función para realizar una busqueda binaria:
def busqueda_binaria(array, valor):
    vector = array
    a = 0
    b = len(array) 
    while a < b:
        m = (a + b) // 2 
        if array[m] == valor:
            return print("El valor encontrado es:",m)
        elif array[m] < valor:
            a = m + 1
        else:
            b = m            
    return print("No encontró el valor que está buscando en las estructuras o arrays")

In [59]:
x1 = [0,1,2,3,4,5,6,7]
x2 = [1,4,8,12,41]
x3 = [0,1,2,4,8,16,32]

In [60]:
busqueda_binaria(x1, 5)

El valor encontrado es: 5
